<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Infrastructure\Models\Interest;

class InterestsSeeder extends Seeder
{
    public function run(): void
    {
        $interests = [
            // Programming & Development
            'Programming',
            'Web Development',
            'Mobile Development',
            'Backend Development',
            'Frontend Development',
            'Full Stack Development',
            'Game Development',
            'Software Engineering',
            'DevOps',
            'Cloud Computing',
            'Database Design',
            'API Development',
            'Open Source Contribution',
            'Code Review',
            'Technical Writing',

            // Popular Programming Languages
            'Python Development',
            'JavaScript Development',
            'TypeScript Development',
            'Java Development',
            'C# Development',
            'C++ Development',
            'PHP Development',
            'Ruby Development',
            'Go Development',
            'Rust Development',
            'Kotlin Development',
            'Swift Development',
            'Objective-C Development',

            // Web-Specific Languages
            'HTML/CSS Development',
            'React Development',
            'Vue.js Development',
            'Angular Development',
            'Node.js Development',
            'Express.js Development',
            'Django Development',
            'Flask Development',
            'Laravel Development',
            'Spring Boot Development',
            'ASP.NET Development',

            // Data & Scientific Languages
            'R Programming',
            'MATLAB Development',
            'Julia Programming',
            'Scala Development',
            'Clojure Development',

            // Functional Programming Languages
            'Haskell Development',
            'Lisp Development',
            'Scheme Development',
            'Elixir Development',
            'Erlang Development',
            'F# Development',

            // Systems & Low-Level Languages
            'Assembly Language',
            'C Development',
            'Zig Development',
            'D Programming',
            'Nim Development',

            // Scripting & Automation Languages
            'Bash Scripting',
            'PowerShell Development',
            'Perl Development',
            'Lua Development',
            'Groovy Development',
            'VB.NET Development',

            // Mobile Development Languages
            'Flutter Development',
            'React Native Development',
            'Xamarin Development',
            'Dart Development',

            // Game Development Languages
            'C# Game Development',
            'C++ Game Development',
            'UnityScript Development',
            'GDScript Development',
            'Lua Game Development',

            // Niche & Emerging Languages
            'Rust Systems Programming',
            'WebAssembly Development',
            'Crystal Development',
            'Raku Development',
            'Racket Development',
            'OCaml Development',
            'Ada Development',
            'COBOL Development',
            'Fortran Development',
            'Prolog Development',
            'Tcl Development',
            'Rebol Development',
            'Forth Development',
            'Smalltalk Development',
            'Eiffel Development',
            'Modula Development',
            'Pascal Development',
            'Delphi Development',
            'AutoHotkey Development',
            'AppleScript Development',
            'VimScript Development',
            'Emacs Lisp Development',

            // Cybersecurity & IT
            'Cybersecurity',
            'Ethical Hacking',
            'Penetration Testing',
            'Network Security',
            'Information Security',
            'Cryptography',
            'Malware Analysis',
            'Security Auditing',
            'Bug Bounty Hunting',

            // AI & Data
            'Artificial Intelligence',
            'Machine Learning',
            'Deep Learning',
            'Data Science',
            'Data Analysis',
            'Natural Language Processing',
            'Computer Vision',
            'Neural Networks',
            'Predictive Modeling',
            'Big Data',
            'Data Visualization',

            // Creative & Design
            'Graphic Design',
            'UI/UX Design',
            'Web Design',
            'Motion Graphics',
            '3D Design',
            'Illustration',
            'Animation',
            'Branding',
            'Logo Design',
            'Typography',
            'Color Theory',
            'Digital Art',
            'Concept Art',

            // Entertainment & Media
            'Gaming',
            'Video Game Development',
            'Esports',
            'Speedrunning',
            'Streaming',
            'Content Creation',
            'Video Production',
            'Filmmaking',
            'Cinematography',
            'Podcasting',
            'Vlogging',
            'YouTube Creation',
            'Twitch Streaming',

            // Music & Audio
            'Music',
            'Music Production',
            'DJing',
            'Sound Design',
            'Audio Engineering',
            'Mixing & Mastering',
            'Composing',
            'Songwriting',
            'Playing Instruments',
            'Singing',
            'Music Theory',
            'Music History',
            'Vinyl Collecting',
            'Concert Going',

            // Sports & Fitness
            'Sports',
            'Fitness',
            'Gym Training',
            'Yoga',
            'Running',
            'Cycling',
            'Swimming',
            'Martial Arts',
            'Rock Climbing',
            'Skateboarding',
            'Surfing',
            'Hiking',
            'Camping',
            'Outdoor Adventures',
            'Team Sports',
            'Esports Training',

            // Reading & Writing
            'Reading',
            'Writing',
            'Blogging',
            'Journaling',
            'Poetry',
            'Fiction Writing',
            'Non-Fiction Writing',
            'Screenwriting',
            'Book Clubs',
            'Literary Analysis',
            'Creative Writing',
            'Storytelling',
            'Fanfiction',
            'World Building',

            // Visual Arts & Photography
            'Photography',
            'Portrait Photography',
            'Landscape Photography',
            'Street Photography',
            'Macro Photography',
            'Photo Editing',
            'Painting',
            'Drawing',
            'Sketching',
            'Sculpture',
            'Printmaking',
            'Collage Art',
            'Mixed Media',

            // Networking & Community
            'Networking',
            'Community Building',
            'Mentoring',
            'Public Speaking',
            'Conferences',
            'Meetups',
            'Collaboration',
            'Team Leadership',
            'Project Management',

            // Hobbies & Lifestyle
            'Cooking',
            'Baking',
            'Culinary Arts',
            'Food Photography',
            'Wine Tasting',
            'Coffee Appreciation',
            'Gardening',
            'Urban Gardening',
            'Plant Care',
            'Aquascaping',
            'Pet Care',
            'DIY Projects',
            'Home Improvement',
            'Interior Design',
            'Furniture Making',
            'Woodworking',
            'Metalworking',
            'Crafting',
            'Knitting',
            'Sewing',
            'Embroidery',
            'Jewelry Making',
            'Leatherworking',

            // Collections & Hobbies
            'Collecting',
            'Vintage Collecting',
            'Action Figure Collecting',
            'Comic Book Collecting',
            'Trading Card Games',
            'Board Games',
            'Tabletop Gaming',
            'Model Building',
            'Miniature Painting',
            'Lego Building',
            'Puzzle Solving',
            'Escape Rooms',

            // Travel & Exploration
            'Travel',
            'Backpacking',
            'Road Trips',
            'Adventure Travel',
            'Cultural Exploration',
            'Local Exploration',
            'Urban Exploration',
            'Photography Travel',

            // Learning & Education
            'Learning',
            'Online Courses',
            'Language Learning',
            'Self-Improvement',
            'Skill Development',
            'Research',
            'Experimentation',
            'Problem Solving',
            'Critical Thinking',

            // Niche & Vague
            'Tinkering',
            'Experimenting',
            'Observing',
            'Thinking',
            'Discussing Ideas',
            'Philosophy',
            'Psychology',
            'Sociology',
            'Anthropology',
            'History',
            'Astronomy',
            'Science',
            'Robotics',
            'Electronics',
            'Arduino Projects',
            'Raspberry Pi Projects',
            'Automation',
            'Optimization',
            'Efficiency',
            'Minimalism',
            'Sustainability',
            'Environmental Activism',
            'Social Causes',
            'Volunteering',
            'Meditation',
            'Mindfulness',
            'Personal Development',
            'Productivity',
            'Time Management',
            'Organization',
            'Nostalgia',
            'Retro Gaming',
            'Emulation',
            'Modding',
            'Customization',
            'Theming',
            'Configuration',
            'Documentation',
            'Archiving',
            'Preservation',
        ];

        foreach ($interests as $interest) {
            Interest::create([
                'name' => $interest,
            ]);
        }
    }
}